//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitiesWinFrameworkAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class communitieswinEntities : DbContext
    {
        public communitieswinEntities()
            : base("name=communitieswinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<vendor_category> vendor_category { get; set; }
        public virtual DbSet<vendor_details> vendor_details { get; set; }
        public virtual DbSet<vendor_product> vendor_product { get; set; }
    }
}
