//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitiesWinFrameworkAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_details
    {
        public long vendor_id { get; set; }
        public string vendor_name { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public long phone { get; set; }
        public string pin { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<bool> is_social_distance { get; set; }
        public Nullable<bool> is_fever_screen { get; set; }
        public Nullable<bool> is_sanitizer_used { get; set; }
        public Nullable<bool> is_stamp_check { get; set; }
        public Nullable<bool> contactless_pay { get; set; }
    }
}
