//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitiesWinFrameworkAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_category
    {
        public long vendor_category_id { get; set; }
        public long category_id { get; set; }
        public long vendor_id { get; set; }
        public bool is_active { get; set; }
    }
}
