//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitiesWinFrameworkAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_product
    {
        public long vendor_product_id { get; set; }
        public long vendor_id { get; set; }
        public long product_id { get; set; }
        public Nullable<decimal> min_order_quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public string Units { get; set; }
    }
}
